### ISSUE TITLE
create a bower.json file to easily install and use your package

### ISSUE THREAD

**Issue by mbelchin** [codemwnci/markdown-editpreview-ng.js#1]
Could be great if you provide a bower.json file with your package to easily use with bower and grunt wiredep

something like this: bower.json

{
  "name": "markdown-editpreview-ng.js",
  "homepage": "https://github.com/codemwnci/markdown-editpreview-ng.js",
  "description": "",
  "version": "1.0.0-rc2",
  "main": [
    "lib/codemwnci/bootstrap-markdown.js",
    "lib/codemwnci/bootstrap-markdown.min.css",
    "lib/codemwnci/markdown-editpreview-ng.js",
    "lib/codemwnci/Markdown.Converter.js",
    "lib/codemwnci/Markdown.Sanitizer.js"
  ],
  "repository": {
    "type": "git",
    "url": "git://github.com/codemwnci/markdown-editpreview-ng.js.git"
  },
  "keywords": [
    "Markdown",
    "editor",
    "angular.js"
  ],
  "authors": [],
  "license": "",
  "ignore": [],
  "dependencies": {},
  "devDependencies": {}
}

Thank you.

**Comment by dokenzy** [comment]
+1

**Comment by codemwnci** [comment]
This has been added, plus I have published it.

```
bower install markdown-editpreview-ng
```

Thank you for the suggestion, and the example bower file.
